#!/usr/bin/env node

var fs = require('fs'), 
    crypto = require('crypto'),
    args = process.argv.slice(2);

var stdin = process.openStdin(), input = '';

var cipher, data = '', encrypted, out, chunk = [],
    packed, decipher,
    encoding = 'base64', 
    algorithm = 'aes256',
    chunk_length = 100,
    password, unpack;

var exit = function (msg, is_error) {
    console.log(msg);
    process.exit(1);
};

var usage = ''
  + '\x1b[1mUsage\x1b[0m: packnode [OPTIONS] <PASSWORD>\n'
  + '\n'
  + '\x1b[1mExample 1\x1b[0m: cat input.js | packnode mypassword > output.js\n'
  + '\x1b[1mExample 2\x1b[0m: cat input.coffee | coffee -c -s | packnode mypassword > output.js\n'
  + '\n'
  + '\x1b[1mOptions\x1b[0m:\n'
  + '  -a, --algorithm <..>   Use the specified algorithm. Default is "aes256"\n'
  + '  -e, --encoding <..>    Encode with base64|hex|binary. Default is "hex"\n'
  + '  -u, --unpack           Unpack the module using the specified password\n'
  + '  -h, --help             Display help information\n'
  ;

if (!args.length) {
    exit(usage);
}

while (args.length) {
    arg = args.shift();
    switch (arg) {
    case '-a':
    case '--algorithm':
        algorithm = args.shift();
        break;
    case '-e':
    case '--encoding':
        encoding = args.shift();
        break;
    case '-u':
    case '--unpack':
        unpack = true;
        break;
    case '-h':
    case '--help':
        exit(usage);
        break;
    default:
        password = arg;
        break;
    }
}

/*
jsmin.js - 2010-01-15
Author: NanaLich (http://www.cnblogs.com/NanaLich)
Another patched version for jsmin.js patched by Billy Hoffman, 
this version will try to keep CR LF pairs inside the important comments
away from being changed into double LF pairs. 

jsmin.js - 2009-11-05
Author: Billy Hoffman
This is a patched version of jsmin.js created by Franck Marcia which
supports important comments denoted with /! ...
Permission is hereby granted to use the Javascript version under the same
conditions as the jsmin.js on which it is based.

jsmin.js - 2006-08-31
Author: Franck Marcia
This work is an adaptation of jsminc.c published by Douglas Crockford.
Permission is hereby granted to use the Javascript version under the same
conditions as the jsmin.c on which it is based.

jsmin.c
2006-05-04

Copyright (c) 2002 Douglas Crockford  (www.crockford.com)

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

The Software shall be used for Good, not Evil.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
String.prototype.has=function(c){return this.indexOf(c)>-1;};function jsmin(input,level,comment){if(!input)return'';if(!level)level=2;if(!comment)comment='';var a='',b='',EOF=-1,LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',DIGITS='0123456789',ALNUM=LETTERS+DIGITS+'_$\\',theLookahead=EOF;function isAlphanum(c){return c!=EOF&&(ALNUM.has(c)||c.charCodeAt(0)>126);}
var iChar=0,lInput=input.length;function getc(){var c=theLookahead;if(iChar==lInput){return EOF;}
theLookahead=EOF;if(c==EOF){c=input.charAt(iChar);++iChar;}
if(c>=' '||c=='\n'){return c;}
if(c=='\r'){return'\n';}
return' ';}
function getcIC(){var c=theLookahead;if(iChar==lInput){return EOF;}
theLookahead=EOF;if(c==EOF){c=input.charAt(iChar);++iChar;}
if(c>=' '||c=='\n'||c=='\r'){return c;}
return' ';}
function peek(){theLookahead=getc();return theLookahead;}
function next(){var c=getc();if(c=='/'){switch(peek()){case'/':for(;;){c=getc();if(c<='\n'){return c;}}
break;case'*':getc();if(peek()=='!'){getc();var d='/*!';for(;;){c=getcIC();switch(c){case'*':if(peek()=='/'){getc();return d+'*/';}
break;case EOF:throw'Error: Unterminated comment.';default:d+=c;}}}else{for(;;){switch(getc()){case'*':if(peek()=='/'){getc();return' ';}
break;case EOF:throw'Error: Unterminated comment.';}}}
break;default:return c;}}
return c;}
function action(d){var r=[];if(d==1){r.push(a);}
if(d<3){a=b;if(a=='\''||a=='"'){for(;;){r.push(a);a=getc();if(a==b){break;}
if(a<='\n'){throw'Error: unterminated string literal: '+a;}
if(a=='\\'){r.push(a);a=getc();}}}}
b=next();if(b=='/'&&'(,=:[!&|'.has(a)){r.push(a);r.push(b);for(;;){a=getc();if(a=='/'){break;}else if(a=='\\'){r.push(a);a=getc();}else if(a<='\n'){throw'Error: unterminated Regular Expression literal';}
r.push(a);}
b=next();}
return r.join('');}
function m(){var r=[];a='';r.push(action(3));while(a!=EOF){switch(a){case' ':if(isAlphanum(b)){r.push(action(1));}else{r.push(action(2));}
break;case'\n':switch(b){case'{':case'[':case'(':case'+':case'-':r.push(action(1));break;case' ':r.push(action(3));break;default:if(isAlphanum(b)){r.push(action(1));}else{if(level==1&&b!='\n'){r.push(action(1));}else{r.push(action(2));}}}
break;default:switch(b){case' ':if(isAlphanum(a)){r.push(action(1));break;}
r.push(action(3));break;case'\n':if(level==1&&a!='\n'){r.push(action(1));}else{switch(a){case'}':case']':case')':case'+':case'-':case'"':case'\'':if(level==3){r.push(action(3));}else{r.push(action(1));}
break;default:if(isAlphanum(a)){r.push(action(1));}else{r.push(action(3));}}}
break;default:r.push(action(1));break;}}}
return r.join('');}
ret=m(input);if(comment){return comment+'\n'+ret;}
return ret;}

// Read from stdin
stdin.setEncoding('utf8');
stdin.on('data', function (input) { data += input; });
stdin.on('end', function () { 

    if (!unpack) {

    // Minify the file
    data = jsmin(data);
    
    // Encrypt the file
    cipher = crypto.createCipher(algorithm, password);
    encrypted = cipher.update(data, 'binary', encoding) + cipher.final(encoding); 
    for (var i = 0, l = encrypted.length; i < l; i += chunk_length) {
        chunk.push(encrypted.substr(i, chunk_length));
    }

    // Prepare the output
    out  = 'e="' + chunk.join('"\n+"') + '";\n';
    out += 'exports.unpack=function(p){var d=require("crypto").createDecipher("' + algorithm + '",p);\n';
    out += 'eval(d.update(e,"' + encoding + '","utf8")+d.final("utf8"));return exports;}';

    } else {
        
        packed = (function () {
            eval(data);
            return e;
        }());
        
        decipher = crypto.createDecipher(algorithm, password);
        
        out = decipher.update(packed, encoding, 'utf8') + decipher.final('utf8');
        
    }
    
    // ..and write to stdout
    process.stdout.write(out);
    
});